name: google-map-generator
description: generate a google map image to dist
author: SN-F-QR

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  google_static_map_api_key:
    description: the api key of google static map
    required: true
  address:
    description:
      the detail address of the map center, see
      https://developers.google.com/maps/documentation/maps-static/start#Addresses
    required: true
    default: 'Shinjuku, Tokyo'
  zoom:
    description:
      the zoom level of the map. Typically ranges from 0 (world view) to 20+
      (building level).
    required: true
    default: '8'
  output:
    description: the output path
    required: true
    default: 'dist/generated-map.png'

runs:
  using: node20
  main: dist/index.js
